---
title: "analyze_power"
format: html
---

```{r}
library(tidyverse)
library(readr)
library(BayesFactor)
```

```{r}

d1 <- read_csv("electrode_data/eeg_binaural_power.csv") |>
  mutate(Condition = as.factor(Condition),
         ROI = as.factor(ROI))

glimpse(d1)

```

```{r}
d2_frontal <- d1 |>
  filter(ROI == "Frontal")

```


```{r}
d2_frontal |>
  ggplot(aes(x=Segment_ID, y=relative_power)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~Condition)
```


```{r}
d1 |>
  ggplot(aes(x=Segment_ID, y=relative_power)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_grid(Condition ~ ROI)
```


```{r}
# 3. Build the Full Bayesian Model (Matches your frequentist formula)
bf_full <- lmBF(Power_20Hz_Norm ~ Condition + Segment_ID, data = d2_frontal)

# 4. Build the Restricted Model (Hypothesis: Condition doesn't matter, only Time does)
bf_restricted <- lmBF(Power_20Hz_Norm ~ Segment_ID, data = d2_frontal)

bf_condition <- bf_full / bf_restricted
```


# Open science

```{r}
o1 <- read_csv("electrode_data/open_power.csv")
```

```{r}
o2_frontal <- o1 |>
  filter(ROI == "Frontal")

```

```{r}
o2_frontal |>
  ggplot(aes(x=Segment_ID, y=relative_power)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~Participant)
```


